# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='subject',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='footer',
            field=models.TextField(default='----'),
        ),
        migrations.AlterField(
            model_name='event',
            name='header',
            field=models.TextField(default='Hi,'),
        ),
    ]
