# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0002_auto_20170212_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
