# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0003_emailschedule_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mail_prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
