# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0004_event_mail_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
