# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0005_person_email_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated', models.BooleanField(default=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sova.Event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sova.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sova.Person')),
            ],
        ),
        migrations.AlterModelOptions(
            name='emailschedule',
            options={'ordering': ('-date',)},
        ),
    ]
