# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0006_auto_20170212_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='group',
        ),
        migrations.AddField(
            model_name='event',
            name='participations',
            field=models.ManyToManyField(through='sova.Participation', to='sova.Person'),
        ),
    ]
