# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-19 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0009_auto_20170219_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 19, 19, 41, 32, 871438, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
