# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0010_participation_date_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
