# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0011_participation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='add_custom_link_before_footer',
            field=models.BooleanField(default=False),
        ),
    ]
