# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0012_emailschedule_add_custom_link_before_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sova.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
