# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0016_event_deadline_for_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='target',
            field=models.IntegerField(choices=[(1, b'Svima u grupi'), (2, b'Onima koji su prihvatili'), (3, b'Onima koji nisu prihvatili'), (4, b'Onima koji nemaju preduvjete'), (5, b'Onima koji imaju preduvjete'), (6, b'Onima koji su sudjelovali')], default=1),
        ),
    ]
