# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0018_auto_20170510_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='type',
            field=models.IntegerField(choices=[(1, 'Obavijest'), (2, 'Pozivnica')], default=1),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='target',
            field=models.IntegerField(choices=[(1, 'Svima u grupi'), (2, 'Onima koji su prihvatili'), (3, 'Onima koji nisu prihvatili'), (4, 'Onima koji nemaju preduvjete'), (5, 'Onima koji imaju preduvjete'), (6, 'Onima koji su sudjelovali')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='footer',
            field=tinymce.models.HTMLField(default='----'),
        ),
        migrations.AlterField(
            model_name='event',
            name='header',
            field=tinymce.models.HTMLField(default='Hi,'),
        ),
    ]
