# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0019_auto_20170510_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
