# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0020_event_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='short_title',
        ),
        migrations.AddField(
            model_name='event',
            name='hype_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
