# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0021_auto_20170510_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
