# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import sova.models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0023_auto_20170514_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='id',
            field=models.IntegerField(default=sova.models.random_es_pkey, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='type',
            field=models.IntegerField(choices=[(1, 'Obavijest'), (2, 'Pozivnica'), (3, 'Anketa nakon događaja')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(default=sova.models.random_p_pkey, primary_key=True, serialize=False),
        ),
    ]
