# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0024_auto_20170523_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAutoParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sova.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sova.Person')),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',)},
        ),
    ]
