# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0025_auto_20170523_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailschedule',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='header',
            field=tinymce.models.HTMLField(default='Hi,\nTko ne dođe na ovu hoo, smrdi!'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mail_prefix',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
