# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0026_auto_20170807_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_organiser', to='sova.Person'),
            preserve_default=False,
        ),
    ]
