# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0027_event_organiser'),
    ]

    operations = [
    ]
