# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0028_person_time_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sova.Event')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='options',
            field=models.ManyToManyField(to='sova.EventOption'),
        ),
    ]
