# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova', '0029_auto_20180526_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='options',
            field=models.ManyToManyField(blank=True, to='sova.EventOption'),
        ),
    ]
